name: My Branch Selenium Test

on:
  push:
    branches:
      - kyanne/profile

jobs:
  run-my-selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install -r requirements.txt || true

      - name: Run my Selenium test
        run: python my_test_script.py
